sonar.projectKey=System-loyalty-customers-backend
sonar.projectName=System-loyalty-customers-backend
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.typescript.tsconfigPath=tsconfig.json

# Вказуємо обидва мікросервіси через кому
sonar.sources=customer-service/src,point-service/src

sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/*.spec.ts,**/*.test.ts,**/*.d.ts

# Додай у кінець sonar-project.properties, щоб знизити стартове дублювання нижче 5%:
sonar.cpd.exclusions=**/RabbitMQPublisher.ts